### ISSUE TITLE
Trade Turn tooltip ambiguity

### ISSUE THREAD

**Issue by astog** [astog/BTS#1]
From @vttale [here](https://github.com/chaorace/cqui/issues/171#issuecomment-268624152)

> Mouseover tooltips for "If started, route will complete in" -- thank you so much for improving on the default game here! -- are off. I can't quite figure out how the number was derived, though.
> 
> For example, I've got one route here which is 38 tiles, and it correctly observes "trips to destination: 1". If then says it would complete in 168 turns. OH WAIT I just figured out where the confusion is, and how it could be addressed. It stems from the clock icon simultaneously being used to mean both relative time and absolute time.
> 
> See, I'm on turn 92. A route that completes in 76 turns would end on turn 168. I recommend for clarity a tooltip that doesn't use the icons and instead reads like:
> 
> Trade Route distance: 38 hexes
> Trips to destination: 1
> If started, route will complete in 76 turns on turn 168
> 
> That would be totally unambiguous.

**Comment by astog** [comment]
Slightly reworded it, but @vttale what do you think?

![Imgur](http://i.imgur.com/WWDHg67.jpg?1)

**Comment by vttale** [comment]
Thanks for working on it.  I'd be satisfied if you closed it, but still think the last "in {clock} 96" would be better as "on turn 96".

**Comment by astog** [comment]
That works 👍 .
