### ISSUE TITLE
"Their Benefits" Visual Not Properly Updating

### ISSUE THREAD

**Issue by Frozen-In-Ice** [astog/BTS#11]
![screenshot 2017-01-09 19 59 45](https://cloud.githubusercontent.com/assets/19610489/21794234/97afb7da-d6c6-11e6-8d5a-381ff510df87.png)
In this screen shot I had selected Delhi which updated the "their benefits" section to display the two gold, but when I went to click on another route the gold icon didn't disappear, so that you can still see it behind the no benefits from route text.

I was using a new install of CQUI as of Jan 9th.

**Comment by astog** [comment]
Oops, missed that. Thanks for discovering it.
