### ISSUE TITLE
Focus path on only route to be created

### ISSUE THREAD

**Issue by vttale** [astog/BTS#12]
When selecting a destination city for a new route, the path displayed should change to only the one for the route, hiding all of the other potential routes to other cities.

**Comment by astog** [comment]
I think it already does that. For instance, if you have a route selected in the *Make a Trade Route* screen, the path only to that destination is shown on the path. If this is not occurring, it is a bug. Can you upload a screenshot of what that looks like?

**Comment by vttale** [comment]
Here Perm to Toronto has been selected.  It was changed from the default of the last route, which had been to Cleveland.

![20170110164016_1](https://cloud.githubusercontent.com/assets/8977507/21825915/9a8eccd8-d753-11e6-984c-785b062b59d1.jpg)

**Comment by astog** [comment]
This is changed with the latest summer patch changes.
