### ISSUE TITLE
Window doesn't scroll when attempting to transfer a trader

### ISSUE THREAD

**Issue by roberto-ii** [astog/BTS#16]
First off... love the mod. 

There is a small bug when there is a large number of owned cities and you attempt to transfer a trader unit to another city where the list of cities does not scroll. I originally found the issue using the current CQUI mod but the same problem exists in BTS from the Workshop. I've attached a couple screen shots that illustrate the problem.

BTS version
![cqui](https://user-images.githubusercontent.com/33436302/33290358-6de25238-d390-11e7-8547-06c512f072f6.jpg)

Non modded version
![original](https://user-images.githubusercontent.com/33436302/33290336-5ed50aec-d390-11e7-92da-142ba51b7d42.jpg)

Thank you

**Comment by astog** [comment]
Thank you for letting me know, I'll fix it for this patch
