### ISSUE TITLE
Feature request:  "total yield score" for route

### ISSUE THREAD

**Issue by vttale** [astog/BTS#8]
I'd like a sort option, in addition to individual yields, for a total yield score.  In my mind what I normally do is just sum everything but take gold at 1/4th rate.  That is, a route that gives 1 bulb, 1 hammer, 1 faith and 4 gold is worth a total of 4 points. 

Another idea, maybe yield-per-total-turns?  Like a total yield score of 10 that takes 50 turns seems somewhat less interesting to me than one that is only a score of 8 but is done in 20 turns.

**Comment by astog** [comment]
Those are definite options, and I will look into them for v3.2, but currently I want to improve the performance of the mod, since it can take quite long late game to open the TradeOverview screen.

**Comment by astog** [comment]
Probably won't get to this, since when picking a route typically a specific yield is of interest, and the sub-sort option kinda accomplishes the same thing. So even if the "best" route in not in the top one, it should be close to the top based on the player requirements.
