### ISSUE TITLE
Add Sort settings pulldown for Change Origin City screen

### ISSUE THREAD

**Issue by astog** [astog/BTS#9]
As the title suggests. Issue ported from user qqqbbb [here](https://forums.civfanatics.com/threads/better-trade-screen.602636/page-8)

Sort settings to add:

- A-Z
- Turn settled

_(If you have any others, please suggest here)_

**Comment by vttale** [comment]
As an option?  One thing I kind of like about the current way is I don't have to remember the names of my most recent cities when I have tons of them, and can just click around the end of the list to find ones that might need boosting.

**Comment by astog** [comment]
I am planning on adding it as a pulldown entry (with all other sort options).

**Comment by astog** [comment]
The cities are now sorted alphabetically A-Z. Getting turn settled is not easy unless hacked codded, which seems too much work for a feature that will get rarely used.
